name: CI/CD for IHSG Forecast Notebook

on:
  workflow_dispatch:

permissions:
  contents: write  # penting supaya GITHUB_TOKEN boleh push

jobs:
  run-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Execute Notebook
        run: jupyter nbconvert --to notebook --execute --inplace Model.ipynb

      - name: Commit and Push Prediction File
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add prediksi_terbaru_rf.csv
          git diff --staged --quiet || git commit -m "Update hasil prediksi terbaru"
          git push
