name: CI/CD for IHSG Forecast Notebook

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute Model.ipynb

      - name: Debug GH_PAT
        run: |
          if [ -z "${GH_PAT}" ]; then
            echo "GH_PAT is empty!"
            exit 1
          else
            echo "GH_PAT is set and length: ${#GH_PAT}"
          fi
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Commit and Push Prediction File
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "DianPandus"
          git config --global user.email "dianpandu25@gmail.com"
          git pull origin main
          git add prediksi_terbaru_rf.csv
          git diff --staged --quiet || git commit -m "Update hasil prediksi terbaru"
          git remote set-url origin https://DianPandus:${GH_PAT}@github.com/DianPandus/forecast_IHSG.git
          git push origin HEAD:main
