# .github/workflows/ci.yml

name: Execute IHSG Forecast Notebook

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Mengunduh kode dari repository
      - name: Check out repository code
        uses: actions/checkout@v4
        # Catatan: 'lfs: true' tidak diperlukan di sini karena
        # berdasarkan screenshot, tidak ada file besar seperti .h5

      # Langkah 2: Menyiapkan lingkungan Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Langkah 3: Menginstall semua library yang dibutuhkan
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Membaca file requirements.txt yang sudah Anda buat
          pip install -r requirements.txt

      # Langkah 4: Menjalankan notebook 'Model.ipynb'
      - name: Execute Jupyter Notebook
        run: |
          # Perintah ini akan menjalankan setiap sel di notebook Anda.
          # Jika ada error, workflow akan gagal.
          jupyter nbconvert --to notebook --execute Model.ipynb
