# .github/workflows/ci.yml

name: Dockerized CI/CD for IHSG Notebook

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ci-docker-notebook
  cancel-in-progress: false

jobs:
  build-run-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ihsg-forecast-app .

      - name: Run Docker container to generate prediction
        run: |
          # Perintah ini menjalankan container.
          # Opsi --mount akan "menyambungkan" folder kerja runner ke folder /app di dalam container.
          # Jadi, saat container membuat file prediksi_terbaru_rf.csv, file itu akan langsung muncul di runner.
          docker run --mount type=bind,source=$(pwd),target=/app ihsg-forecast-app

      - name: Pull latest changes
        run: git pull origin main
      
      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update hasil prediksi terbaru"
          git push origin main
