name: CI/CD for IHSG Forecast Notebook

on:
  push:
    branches: [ "main" ]

jobs:
  run-notebook-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Mengunduh kode dari repository (Bagian CI)
      - name: Check out repository code
        uses: actions/checkout@v4

      # Langkah 2: Menyiapkan lingkungan Python (Bagian CI)
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Langkah 3: Menginstall semua library yang dibutuhkan (Bagian CI)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Langkah 4: Menjalankan notebook untuk menghasilkan prediksi (Bagian CI)
      - name: Execute Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute Model.ipynb

      # Langkah 5: Commit dan Push Hasil Prediksi (Bagian CD, dengan PAT)
      - name: Commit and Push Prediction File
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add prediksi_terbaru_rf.csv
          # Hanya commit dan push jika ada perubahan pada file prediksi
          git diff --staged --quiet || git commit -m "Update hasil prediksi terbaru"
          git push https://DianPandus:${GH_PAT}@github.com/DianPandus/forecast_IHSG.git HEAD:main
