name: IHSG Forecast - Docker CI

on:
  workflow_dispatch: {}
  push:
    branches: [main]
    paths:
      - "Model.ipynb"
      - "Model.py"
      - "requirements.txt"
      - "Dockerfile"
      - ".github/workflows/**"
  schedule:
    - cron: "0 1 * * *" # 08:00 WIB

permissions:
  contents: write
  packages: write # << perlu untuk push ke GHCR

concurrency:
  group: ci-notebook
  cancel-in-progress: true

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/ihsg-forecast

jobs:
  build-run-commit-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global pull.rebase true
          git config --global safe.directory "$GITHUB_WORKSPACE"

      - name: Build Docker image
        run: docker build -t ihsg-forecast:latest .

      - name: Execute notebook inside container
        run: |
          docker run --rm \
            -v "$GITHUB_WORKSPACE":/app \
            -w /app \
            -e CUDA_VISIBLE_DEVICES= \
            -e TF_CPP_MIN_LOG_LEVEL=2 \
            -e TF_ENABLE_ONEDNN_OPTS=0 \
            ihsg-forecast:latest \
            jupyter nbconvert --to notebook --execute --inplace Model.ipynb

      - name: Stage outputs
        run: |
          git add Model.ipynb || true
          if [ -f prediksi_terbaru_rf.csv ]; then git add prediksi_terbaru_rf.csv; fi

      - name: Commit if changes exist
        run: |
          if ! git diff --staged --quiet; then
            git commit -m "Update hasil prediksi terbaru"
          else
            echo "No changes to commit."
          fi

      - name: Rebase onto latest main
        run: |
          git fetch origin main
          git rebase origin/main || (echo "Rebase gagal; coba FF-only" && git rebase --abort && git pull --no-rebase --ff-only origin main)

      - name: Push to main (with retry)
        run: |
          (git push origin HEAD:main) || (
            echo "Push ditolak; fetch+rebase ulang lalu push..."
            git fetch origin main
            git rebase origin/main
            git push origin HEAD:main
          )

      # ======== PUBLISH IMAGE KE GHCR ========
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag image variants
        id: tagger
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          DATE_TAG=$(date -u +'%Y%m%d%H%M')
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_OUTPUT
          echo "DATE_TAG=$DATE_TAG"   >> $GITHUB_OUTPUT
          docker tag ihsg-forecast:latest $IMAGE_NAME:latest
          docker tag ihsg-forecast:latest $IMAGE_NAME:sha-${SHORT_SHA}
          docker tag ihsg-forecast:latest $IMAGE_NAME:date-${DATE_TAG}

      - name: Push images (latest + sha + date)
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:sha-${{ steps.tagger.outputs.SHORT_SHA }}
          docker push $IMAGE_NAME:date-${{ steps.tagger.outputs.DATE_TAG }}

      - name: Push version tag on git tag (optional)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"
          docker tag ihsg-forecast:latest $IMAGE_NAME:${VERSION}
          docker push $IMAGE_NAME:${VERSION}
